[package]
name = "palmodmanager"
version = "1.7.0"
edition = "2021"
default-run = "palmodmanager"



[lib]
name = "palmodmanager_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-single-instance = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = { version = "2", default-features = false, features = ["deflate", "bzip2", "lzma", "zstd", "time"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
walkdir = "2"
reqwest = { version = "0.12", features = ["json", "gzip", "brotli"] }
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.22"
hostname = "0.4"
junction = "1.0.0"
pathdiff = "0.2"
notify = "6.1.1"
sha2 = "0.10"
url = "2"
winreg = "0.52"
open = "5"
regex = "1"
sevenz-rust = { version = "0.6.1", features = ["aes256", "bzip2", "zstd"] }
repak = { git = "https://github.com/trumank/repak", features = ["oodle"] }
uesave = "0.7.1"
unreal_asset = "0.1"
flate2 = "1.0"
lz4_flex = "0.11"
oozextract = "0.5.4"
texture2ddecoder = "0.1"
byteorder = "1.5"
