import { createScope } from '../core/query';

export interface SettingsDomMap {
  'settings-modal': HTMLElement;
  'settings-modal-close-x': HTMLButtonElement;
  'settings-pane-game': HTMLElement;
  'settings-game-path': HTMLInputElement;
  'settings-browse-btn': HTMLButtonElement;
  'settings-path-status': HTMLElement;
  'settings-data-path-select': HTMLSelectElement;
  'settings-custom-data-path-display': HTMLElement;
  'open-folder-paks': HTMLButtonElement;
  'open-folder-ue4ss': HTMLButtonElement;
  'open-folder-palschema': HTMLButtonElement;
  'open-folder-appdata': HTMLButtonElement;
  'open-folder-profile': HTMLButtonElement;
  'settings-pane-nexus': HTMLElement;
  'settings-nexus-account-card': HTMLElement;
  'nexus-nxm-status-badge': HTMLElement;
  'nexus-nxm-current-handler': HTMLElement;
  'nexus-nxm-actions': HTMLElement;
  'nexus-protocol-status-badge': HTMLElement;
  'nexus-protocol-actions': HTMLElement;
  'nexus-manual-callback-input': HTMLInputElement;
  'btn-nexus-manual-callback': HTMLButtonElement;
  'settings-pane-mods': HTMLElement;
  'settings-hide-native-mods': HTMLInputElement;
  'settings-force-load-order-ue4ss': HTMLInputElement;
  'settings-force-load-order-palschema': HTMLInputElement;
  'settings-debug-console': HTMLInputElement;
  'settings-pane-interface': HTMLElement;
  'settings-language-select': HTMLSelectElement;
  'settings-folder-expand-mode-select': HTMLSelectElement;
  'theme-toggle-btn': HTMLButtonElement;
  'settings-toolbar-scale': HTMLInputElement;
  'settings-toolbar-scale-value': HTMLElement;
  'settings-pane-network': HTMLElement;
  'settings-dns-resolver-select': HTMLSelectElement;
  'settings-usmap-badge': HTMLElement;
  'settings-usmap-details': HTMLElement;
  'settings-usmap-game-ver': HTMLElement;
  'settings-usmap-active-file': HTMLElement;
  'settings-usmap-hash': HTMLElement;
  'btn-sync-usmap': HTMLButtonElement;
  'btn-sync-usmap-icon': HTMLElement;
  'settings-image-cache-badge': HTMLElement;
  'btn-purge-image-cache': HTMLButtonElement;
  'settings-pane-safety': HTMLElement;
  'safety-backup-status-text': HTMLElement;
  'safety-restore-btn': HTMLButtonElement;
  'safety-backup-now-btn': HTMLButtonElement;
  'reset-workshop-cache-btn': HTMLButtonElement;
  'storage-temp-badge': HTMLElement;
  'storage-temp-details': HTMLElement;
  'storage-clear-temp-btn': HTMLButtonElement;
  'storage-open-temp-btn': HTMLButtonElement;
  'storage-library-badge': HTMLElement;
  'storage-library-details': HTMLElement;
  'storage-open-library-btn': HTMLButtonElement;
  'storage-images-badge': HTMLElement;
  'storage-images-details': HTMLElement;
  'storage-clear-images-btn': HTMLButtonElement;
  'settings-cancel': HTMLButtonElement;
  'settings-save': HTMLButtonElement;
}

export const settingsDom = createScope<SettingsDomMap>('settings');
